"""Added a task_done column

Revision ID: 95353a32a272
Revises: 254ea5940be7
Create Date: 2024-05-18 19:35:47.811423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95353a32a272'
down_revision = '254ea5940be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_done', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('task_done')

    # ### end Alembic commands ###
